# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b387a361bae7323674116c329314f6d972e9d52e18e2ddb8f3bcaedd970979aa5634f157c903e0a200f4b85480ac8b45e48fb7da3ab7c7e4e6b509b67fe4b670

test:
  secret_key_base: ab373735a5b9df08118c9043e7d466b9ef3d43bf71fc62990582b3cba5dfb3bed75c2a34d957352fdaba7d2674b5a0150cc83f9909639e43ffd706af1f2a1414

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
